### ISSUE TITLE
ESPHome reports failed but upgrade is completed based on OTA Feedback

### ISSUE THREAD

**Issue by joaovitoriasilva** [mmakaay/esphome-yeelight_bs2#72]
Updated ESPHome to latest version and requested to updated lamps firmware. I did, the update seems sucessful looking to the OTA Feedback (green at the end) and then I get these errors:

RAM:   [=         ]   9.9% (used 32328 bytes from 327680 bytes)
Flash: [====      ]  44.7% (used 819817 bytes from 1835008 bytes)
Building .pioenvs/bedsidelampdiana/firmware.bin
========================= [SUCCESS] Took 13.34 seconds =========================
INFO Successfully compiled program.
INFO Connecting to 192.168.3.231
INFO Uploading /config/.esphome/build/bedsidelampdiana/.pioenvs/bedsidelampdiana/firmware.bin (819952 bytes)
Uploading: [============================================================] 100% Done...

INFO Waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from 192.168.3.231 using esphome API
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/esphome/__main__.py", line 823, in main
    return run_esphome(sys.argv)
  File "/usr/local/lib/python3.9/dist-packages/esphome/__main__.py", line 810, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/usr/local/lib/python3.9/dist-packages/esphome/__main__.py", line 391, in command_run
    return show_logs(config, args, port)
  File "/usr/local/lib/python3.9/dist-packages/esphome/__main__.py", line 282, in show_logs
    return run_logs(config, port)
  File "/usr/local/lib/python3.9/dist-packages/esphome/components/api/client.py", line 72, in run_logs
    asyncio.run(async_run_logs(config, address))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/esphome/components/api/client.py", line 24, in async_run_logs
    zc = zeroconf.Zeroconf()
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 447, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_utils/net.py", line 373, in create_sockets
    if add_multicast_member(cast(socket.socket, listen_socket), i):
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_utils/net.py", line 288, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available

**Comment by mmakaay** [comment]
I have never seen this error. It looks like flashing is successful indeed. After flashing the client tries to connect to the logger API, but that fails.

Can you view the log output for the device when starting those?

**Comment by mmakaay** [comment]
Any progress on this, or can I close this ticket?
